### ISSUE TITLE
Check for updates in pdf viewer dependencies

### ISSUE THREAD

**Issue by bianchimro** [C2DH/ww1#111]

**Comment by bianchimro** [comment]
https://github.com/mikecousins/react-pdf-js

**Comment by bianchimro** [comment]
@uf0 with new version of the package we're using (seems the best option) there is a new option called "fitWidth" (working, while "fillHeight" does not seem to work).

Proposal: we could add a "fit width" button alternative to manual zoom.

**Comment by uf0** [comment]
it's not possible to add a "fitHeight" button? and by default have the pdf adapted to the width?
