### ISSUE TITLE
Add Google Analytics before the release

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/ww1#116]

**Comment by gffuma** [comment]
https://github.com/C2DH/ww1/commit/848dc3732eec7a9c7fd64fd52e0ff9497569b8ce#diff-14b1e33d5bf5649597cdc0e4f684daddR82

When we are ready to final deploy just uncomment the commented line to activate Google Analytics

**Comment by danieleguido** [comment]
Hi @gffuma,
is it possible to use a .env files to store the GAid it?
