### ISSUE TITLE
Themes are not visible when user is logged in the same browser

### ISSUE THREAD

**Issue by danieleguido** [C2DH/ww1#121]
Also note that api output is the same

**Comment by bianchimro** [comment]
hi @danieleguido I think this depends on being logged on the miller admin
You could probably fix it by removing the  'rest_framework.authentication.SessionAuthentication' class from rest framework settings:

```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
         ...
        'rest_framework.authentication.SessionAuthentication',
    )
}
```

**Comment by danieleguido** [comment]
Thanks @bianchimro
