### ISSUE TITLE
/themes arrow keys not working for navigation

### ISSUE THREAD

**Issue by danieleguido** [C2DH/ww1#174]

**Comment by uf0** [comment]
do we want this feature? we have already scroll and click

**Comment by danieleguido** [comment]
then just remove the "scroll or use the arrows to read the story" :D https://ww1.lu/themes/the-occupation-2/chapters/chapter-1?lang=en

**Comment by uf0** [comment]
We meant arrow buttons.
Feel free to provide a better translation or confirm the removal

**Comment by uf0** [comment]
It Became a translation issue, I close it
