### ISSUE TITLE
/themes module text + gallery documents detail button is not present

### ISSUE THREAD

**Issue by danieleguido** [C2DH/ww1#175]
E.g. https://ww1.lu/themes/the-occupation-2/chapters/chapter-4/modules/3?lang=en

**Comment by uf0** [comment]
Just a matter of css positioning
<img width="130" alt="screen shot 2018-03-06 at 16 16 27" src="https://user-images.githubusercontent.com/1922342/37040306-ce36b4aa-2159-11e8-9633-8c7660b926b4.png">
