### ISSUE TITLE
/item detail (sporadic) part of images are not loaded.

### ISSUE THREAD

**Issue by danieleguido** [C2DH/ww1#187]
Apparently this is non connected to bandwith / network since images are correctly delivered.

**Comment by lwieneke** [comment]
![postcard_showing_a_scene_from_oscar_straus___der_tapfere_soldat_](https://user-images.githubusercontent.com/1942767/37968428-5e1ae1fc-31ce-11e8-9c65-a7205a51b4cb.jpg)

Issue can be reproduced on Safari by opening different image items from the collection.

**Comment by uf0** [comment]
Agreed with @danieleguido to load reduced size image

**Comment by lwieneke** [comment]
@uf0 I don't think file size is the issue at hand. We'll investigate further and add additional information once we find further evidence.
