### ISSUE TITLE
Modify instructions for navigation in themes

### ISSUE THREAD

**Issue by lwieneke** [C2DH/ww1#190]
Currently the description reads: 
"use your mouse or the arrows to read the story"
as keyboard navigation is supposed to be deactivated this should read
"use your mouse or the arrow buttons to read the story"

**Comment by uf0** [comment]
All the texts related to the interface can be updated from a specific spreadsheet provided by @danieleguido

**Comment by lwieneke** [comment]
Roger that. I just can't assign anybody to the task but this was meant for Daniele or better: our side

**Comment by danieleguido** [comment]
@lwieneke what will be its translation in German?

**Comment by lwieneke** [comment]
I'd say:
Klicken Sie auf die Pfeile um die Geschichte zu lesen

(in that case I'd leave out mouse or screen scroll but the text would just too long in that case)

**Comment by danieleguido** [comment]
@lwieneke  we currently have `scrolle oder nutze die Pfeile um die Geschichte zu lesen` is this the latest one?

**Comment by lwieneke** [comment]
Nope, that was the initial one.
After careful consideration please use the following line:
"Scrollen oder klicken Sie auf die Pfeile um den Artikel zu lesen"
