### ISSUE TITLE
/resources preview images truncated

### ISSUE THREAD

**Issue by lwieneke** [C2DH/ww1#191]
The preview image for the resources is truncated
![screen shot 2018-03-29 at 18 02 25](https://user-images.githubusercontent.com/1942767/38128670-cfdf77e2-33fb-11e8-9440-87e33516c634.png)

**Comment by lwieneke** [comment]
.ResourceCard__image
width: 255px 
should be 100%

![resources](https://user-images.githubusercontent.com/1942767/38128704-fc53a8e8-33fb-11e8-9e27-441c50ff8eea.jpg)

**Comment by uf0** [comment]
Already fixed here https://github.com/C2DH/ww1/commit/cbd15613a7db27562400e06e362e6bb7894c2718
