### ISSUE TITLE
add contact form link

### ISSUE THREAD

**Issue by uf0** [C2DH/ww1#193]
https://github.com/C2DH/ww1/blob/master/src/components/Layout/OpenSideMenu/OpenSideMenu.js#L46

`<li><a href="your link"> {this.context.t('YOUR TITLE KEY')} </a></li>`

**Comment by danieleguido** [comment]
@uf0 how to get the current language and current page? I'd like to do something like:

`<li><a href="/contact-us/?lang=fr&next=/collection">`
