### ISSUE TITLE
Fullscreen video

### ISSUE THREAD

**Issue by bianchimro** [C2DH/ww1#97]
Toggles prev module

**Comment by bianchimro** [comment]
@danieleguido @uf0 can you please add a video module to the editor (we cannot debug otherwise)

**Comment by uf0** [comment]
/themes/occupation/chapters/test-title/modules/1?lang=en

**Comment by bianchimro** [comment]
@ufo the data of the module seems incomplete, no url....

**Comment by bianchimro** [comment]
https://github.com/video-react/video-react/blob/master/src/components/control-bar/FullscreenToggle.js
